### ISSUE TITLE
Insufficient axis homed when changing tool before homing

### ISSUE THREAD

**Issue by martijnschouten** [diabase/H-Series-Configuration#15]
Not sure if this is a bug or if it is necessary, but Cura request a tool-change at the first line of any gcode. With the new toolchanging macros this causes an error in case the printer has not been homed yet. The error is:
```
moving z position to34.400
Error: G0/G1: insufficient axes homed
```

**Comment by RonaldThomas** [comment]
Hi Martijn,
Because tool changing requires physical movement of the machine, it is indeed necessary that the axes be homed before a tool selection can occur. We are working on streamlining the interface between Cura and the H-Series machines, so watch this space.
