### ISSUE TITLE
Blank Interference

### ISSUE THREAD

**Issue by GurminderSUCD** [diabase/H-Series-Configuration#16]
I was trying to update the firmware. After step 3.4 (3.4. Refresh your browser.), the interference becomes blank. I tried to configure it again with YAT. But nothing is working. The machine is showing connected but the interference is blank. Can you help?

**Comment by RonaldThomas** [comment]
Hi, Gurminder! Thanks for letting us know. We received your support email and will be reaching out to you directly via email.
